spring:
        # h2.console:
           #     enabled: true
           #       path: /h2
       datasource.url: jdbc:postgresql://192.168.0.142/DbAula

       datasource:
                   username: joaojsrbr
                   password: 123
                   driver-class-name: org.postgresql.Driver
            jpa:
                hibernate.ddl-auto: none
                properties.hibernate.format_sql: true
                show-sql : true